version: '3.8'
services:
  mongodb:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mydatabase
    depends_on:
      - mongodb

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  mongo-data:
